### ISSUE TITLE
AttributeError: 'KNeighborsClassifier' object has no attribute 'n_samples_fit_'

### ISSUE THREAD

**Issue by farzadmohseni-ir** [JafarAkhondali/Iran-credit-card-ocr#4]
**_When running with Python 3.8.3 , even though all the libraries are installed, I get the following error :_**

> Traceback (most recent call last):
  File "main.py", line 488, in <module>
    cc, bank_name = run(img_name)
  File "main.py", line 456, in run
    c = try_ocr(d1)
  File "main.py", line 177, in try_ocr
    classify = inputdata(img_copy)
  File "main.py", line 69, in inputdata
    return predict_knn(H)
  File "main.py", line 54, in predict_knn
    predict = knn.predict(df.reshape(1, -1))[0]
  File "C:\Users\farza\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\neighbors\_classification.py", line 173, in predict
    neigh_dist, neigh_ind = self.kneighbors(X)
  File "C:\Users\farza\AppData\Local\Programs\Python\Python38\lib\site-packages\sklearn\neighbors\_base.py", line 613, in kneighbors
    n_samples_fit = self.n_samples_fit_
**AttributeError: 'KNeighborsClassifier' object has no attribute 'n_samples_fit_'**

**_why ?_**

**Comment by alpersarac** [comment]
same here I couldn't solve that issue, did you find the solution do you mind if you share with me?
